name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  upload:
    name: Upload release
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Delete old release and tag
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          delete_release: true
          tag_name: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release to GitHub
        uses: ncipollo/release-action@v1
        with:
          name: Latest Version
          tag: latest
          commit: main
          body: "${{ github.event.head_commit.url }} ${{ github.event.head_commit.message }}"
          artifacts: "v3.2.10.tgz"
          prerelease: false
